name: deploy

on:
  push:
    branches:
      - 'master'

env:
  IMAGE: registry.hub.docker.com/andrewklyuchnikov/leaders-frontend
  REGISTRY_URL: 'registry.hub.docker.com'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          cache-from: ${{ env.IMAGE }}:latest
          build-args: VITE_API_URL=${{ vars.BACKEND_URL }}
          push: true
          tags: ${{ env.IMAGE }}:latest,${{ env.IMAGE }}:${{ github.sha }}

      - name: send telegram message on fail build
        uses: appleboy/telegram-action@master
        if: ${{ failure() }}
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ❌ Failed to build!

            Commit message: ${{ github.event.commits[0].message }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

            See job logs: ${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY }}/actions/runs/${{ env.GITHUB_RUN_ID }}"


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Get Known Hosts
        id: get_known_hosts
        run: |
          KNOWN_HOSTS=$(ssh-keyscan -H ${{ secrets.SSH_HOST }})
          echo ::set-output name=hosts::${KNOWN_HOSTS}

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ steps.get_known_hosts.outputs.hosts }}

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy.yml
          directory: ./ansible
          options: |
            --inventory hosts
            --verbose
            -e DOCKER_REGISTRY=${{ env.REGISTRY_URL }}
            -e DOCKER_PASSWORD=${{ secrets.DOCKERHUB_TOKEN }}
            -e DOCKER_USER=${{ secrets.DOCKERHUB_USERNAME }}
            -e app_image_version=${{ github.sha }}

      - name: send telegram message on deploy
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Frontend was deployed by ${{ github.actor }}

            Commit message: ${{ github.event.commits[0].message }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            
            See result: https://leaders.rubles.lol/

      - name: send telegram message on failure
        uses: appleboy/telegram-action@master
        if: ${{ failure() }}
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ❌ Failed to deploy!

            Commit message: ${{ github.event.commits[0].message }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            
            See job logs: ${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY }}/actions/runs/${{ env.GITHUB_RUN_ID }}"
